# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emakina.FR - Blog technique
description: Le blog où nos experts parlent de leur quotidien dans le monde du développement.
permalink: /:title:output_ext

lang: fr
show_excerpts: true
google_analytics: UA-NNNNNNNN-N   # TODO
timezone: Europe/Paris
exclude:
  - .git/
  - .idea/

header_pages:
  - categories.liquid

# Build settings
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: jekyll/minima

# Theme settings (https://github.com/jekyll/minima)
minima:
  date_format: "%-d %b %Y"
  skin: dark
  social_links:
    github: EmakinaFR
    linkedin: emakina-fr
    twitter: emakinaFR
